name: Format and merge PRs

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  format-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/merge'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'
        
      - uses: actions/checkout@v1
        if: steps.check.outputs.triggered == 'true'

      - name: Use Node.js 12.x
        if: steps.check.outputs.triggered == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        if: steps.check.outputs.triggered == 'true'
        run: yarn install

      - name: Run prettier
        if: steps.check.outputs.triggered == 'true'
        run: yarn run prettier --write 'src/**/*.js'
   
      - name: push
        uses: github-actions-x/commit@v2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Prettier'
        
      - uses: maxkomarychev/merge-pal-action@v0.5.1
        if: steps.check.outputs.triggered == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
